// <auto-generated />
using System;
using BelbimEShop.Catalog.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelbimEShop.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelbimEShop.Catalog.Domain.Aggregates.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(7614),
                            Description = "Her türlü ev elektroniği",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(7628),
                            Description = "Her türlü kitap",
                            Name = "Kitap"
                        });
                });

            modelBuilder.Entity("BelbimEShop.Catalog.Domain.Aggregates.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(8151),
                            Description = "4K Ultra HD Smart TV",
                            Name = "Televizyon",
                            Price = 4999.99m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(8164),
                            Description = "Yüksek performanslı dizüstü bilgisayar",
                            Name = "Laptop",
                            Price = 7999.99m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(8169),
                            Description = "Bertrand Russel",
                            Name = "Zihnin analizi",
                            Price = 100m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 4, 11, 30, 23, 378, DateTimeKind.Utc).AddTicks(8173),
                            Description = "Jean Paul Sartre",
                            Name = "Varlık ve Hiçlik",
                            Price = 150m,
                            Stock = 1
                        });
                });

            modelBuilder.Entity("BelbimEShop.Catalog.Domain.Aggregates.Product", b =>
                {
                    b.HasOne("BelbimEShop.Catalog.Domain.Aggregates.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BelbimEShop.Catalog.Domain.Aggregates.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
